### ISSUE TITLE
TeamStatsCalculator has instances of duplicate code (in parvane branch)

### ISSUE THREAD

**Issue by m-parvaneh** [CSC207-UofT/course-project-team-scouts#10]
The implementations of the two methods in the TeamStatsCalculator are very similar (as the functionality is similar). It might be cleaner to abstract this similar logic out into a helper method of some kind. (Currently, the implementation is only located in the parvane branch)

**Comment by 1izardo** [comment]
@m-parvaneh Is this issue still present? Feel free to close this if it's been resolved.

**Comment by m-parvaneh** [comment]
I had been thinking of ways to refactor the code in this class such that I could extract duplicate code into a helper method, however, it turns out that doing this would not actually have a simple solution. As I was trying it out, I felt that I was only adding more unnecessary bulk and complexity to the code, so I am leaving it as is. Closing the issue as well.
