### ISSUE TITLE
Builder design pattern can be expanded

### ISSUE THREAD

**Issue by Kaartik7** [CSC207-UofT/course-project-team-scouts#16]
The current utility of builder design pattern in our code is very basic; builder design pattern comes in very helpful while building complex objects step by step, perhaps in future we can expand its utility to create more complex objects

**Comment by 1izardo** [comment]
Closing this issue, since our specification doesn't require creating more complex objects. `InputBuilder` is being used to extract logic out of `CommandLine`, which is all we need for our use case.
